[package]
name = "bin"
version = "0.1.0"
edition = "2021"

[dependencies]
exports = { version = "0.1.0", path = "../exports" }
libloading = "0.8.4"
rubicon = { version = "2.0.0", path = "../../rubicon" }
soprintln = { version = "3.0.0", features = ["print"] }
