name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
      fail-fast: false

    steps:
      - uses: actions/checkout@v2
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
      - name: Run cargo command
        run: |
          cargo run --manifest-path test-crates/bin/Cargo.toml
        continue-on-error: ${{ matrix.os == 'windows-latest' }}
      - name: Run cargo command (release)
        run: |
          cargo run --manifest-path test-crates/bin/Cargo.toml --release
        continue-on-error: ${{ matrix.os == 'windows-latest' }}
      - name: Run cargo command (release with SOPRINTLN=1)
        if: matrix.os != 'windows-latest'
        run: |
          export SOPRINTLN=1
          cargo run --manifest-path test-crates/bin/Cargo.toml --release
